/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mongodb;

import org.junit.Test;
import static org.junit.Assert.*;

public class UtilidadesTest {
    @Test public void testSomeLibraryMethod() {
        
    Utilidades classUnderTest = new Utilidades();
       
        assertNotNull("probando conexion", classUnderTest.getConnection("prueba"));
    }
}
